#### NumPy - Numerical Python

##### NumPy Array

no. of dimensions = rank

shape = tuple of ints giving size along each dimension

In [3]:
import numpy as np

In [4]:
narr1=np.array([1,2,3,4,5],dtype=int)
narr1

array([1, 2, 3, 4, 5])

In [5]:
narr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
narr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print(type(narr1))
print(type(narr2))
print(narr1.ndim)
print(narr2.ndim)
print(narr1.shape)
print(narr2.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1
2
(5,)
(3, 3)


In [7]:
print(type(narr1[1]))

<class 'numpy.int32'>


In [8]:
list1=[4,5,6]
print(type(list1))

<class 'list'>


In [9]:
print(type(narr2[1]))

<class 'numpy.ndarray'>


In [10]:
narr2[1]

array([4, 5, 6])

In [11]:
type(narr2[1])

numpy.ndarray

In [12]:
narr3=np.array([[1,2,3,4],[5,6,7,8]])
narr3.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
narr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
narr3=narr3.reshape(4,2)

In [15]:
narr3.shape

(4, 2)

In [16]:
list1=[1,2]
list2=[3,4]
list3=[5,6]
narr4=np.array([list1,list2,list3])
narr4

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
range1=range(24)
print(range1)

range(0, 24)


In [18]:
nran1=np.arange(24)
print(nran1)
print(nran1.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


ndim is a NumPy attribute. ALWAYS means Number of Dimensions, hence 'ndim'

In [19]:
narr5=np.array([[1,2],[3,4],[5,6],[7,8]])
narr5

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
narr6=narr3+narr5
narr7=np.add(narr3,narr5)

In [21]:
print(narr6)
print(narr7)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [22]:
print(narr6-narr5)
print(np.subtract(narr7,narr3))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [23]:
print(narr3*narr5)
print(np.multiply(narr6,narr7))

[[ 1  4]
 [ 9 16]
 [25 36]
 [49 64]]
[[  4  16]
 [ 36  64]
 [100 144]
 [196 256]]


In [24]:
print(narr3.dot(narr5.reshape(2,4)))
print(np.dot(narr6,narr7.reshape(2,4)))

[[11 14 17 20]
 [23 30 37 44]
 [35 46 57 68]
 [47 62 77 92]]
[[ 44  56  68  80]
 [ 92 120 148 176]
 [140 184 228 272]
 [188 248 308 368]]


In [26]:
print(narr7/narr3)

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]
